version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/api
    environment:
      - ROCKET_ADDRESS=0.0.0.0
      - ROCKET_PORT=7779
    ports:
      - 7779:7779